services:
  php:
    build:
      context: .
    volumes:
      - ./src:/var/www
    networks:
      - desafio_irede

  nginx:
    image: nginx:alpine
    ports:
      - "20080:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - desafio_irede
    depends_on:
      - php

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: desafio_irede
      MYSQL_USER: desafio_irede
      MYSQL_PASSWORD: secret
    volumes:
      - ./docker/data:/var/lib/mysql
    ports:
      - "23306:3306"
    networks:
      - desafio_irede

networks:
  desafio_irede:
    driver: bridge
